# Generated by Django 5.2 on 2025-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Minimum 50 characters.')),
                ('project_type', models.CharField(max_length=100)),
                ('other_project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('other_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_to', models.CharField(choices=[('individual', 'Individual Users'), ('organization', 'Organizations'), ('both', 'Both')], max_length=30)),
                ('approx_users', models.CharField(choices=[('upto_100', 'Up to 100'), ('100_1000', '100–1,000'), ('1000_10000', '1,000–10,000'), ('10000_100000', '10,000–100,000'), ('100000_plus', '100,000+')], max_length=30)),
                ('version_needed', models.CharField(choices=[('mvp', 'MVP'), ('full', 'Fully Featured Solution'), ('both', 'Both')], max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('office_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('requested_meeting', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('MEETING_REQUESTED', 'Meeting Requested'), ('MEETING_SENT', 'Meeting Link Sent'), ('IN_DISCUSSION', 'In Discussion'), ('IN_PROGRESS', 'In Progress'), ('HALTED', 'Halted'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=30)),
                ('progress_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
